project:
  type: website
  render:
    - index.qmd
    - paper.qmd
    - data-science.qmd
    - about.qmd
    - people.qmd
    - publications.qmd
    - projects.qmd
    - degrees.qmd
    - collaborations.qmd
    - contact.qmd
    - software.qmd
    - blog.qmd
    - posts/**/*.qmd

website:
  title: "DST"
  site-url: https://itsleeds.github.io/dst/
  description: "Data Science and Transport Theme website for the University of Leeds"
  repo-url: https://github.com/itsleeds/dst
  repo-actions: [edit, issue]
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Open Source Software"
        href: software.qmd
      - text: "Data Science & Technology"
        menu:
          - text: "Overview"
            href: data-science.qmd
          - text: "About"
            href: about.qmd
          - text: "People"
            href: people.qmd
          - text: "Publications"
            href: publications.qmd
          - text: "Projects"
            href: projects.qmd
          - text: "Research degrees"
            href: degrees.qmd
          - text: "Collaborations"
            href: collaborations.qmd
          - text: "Contact"
            href: contact.qmd
    right:
      - icon: rss
        href: blog.xml
