---
title: Data Science and Technology
---

Data Science and Technology (DST) is a theme within the Institute for Transport Studies at the University of Leeds that applies new digital technologies to answer research questions and inform decision-making in transport planning, operations, and policy.
The theme brings together experts in data science, transport modelling, and the use of broadly-defined artificial intelligence techniques to address challenges in the transport sector.
Although the focus is on new methods and technologies, our aim has an important social dimension: we believe in reducing barriers to accessing and using data and digital tools to improve transport systems for all users.

Our work covers a range of topics, including:

- The application of data science techniques to transport research questions and applications
- The development of transport methods, models, and tools to support better decision-making
- The use of computer vision and other machine learning techniques to extract insights from transport-related datasets
- The use of artificial intelligence to improve transport systems



